name: SellEXP
api: [3.0.0-ALPHA10]
main: SellEXP\Main
version: 0.0.1-ALPHA
author: VMPE Development Team
commands:
  sellexp:
    description: "Sells the item in your hand or all of your inventory's contents"
    permission: sellexp.command
permissions:
  sellexp:
    default: true
    children:
      sellexp.amount:
        default: true
      sellexp.all:
        default: true
      sellexp.command:
        default: true
